### ISSUE TITLE
Fml Log Error

### ISSUE THREAD

**Issue by Dream-Master** [fewizz/NotEnoughThaumcraftTabs-issue-tracker#1]
I have this error in my fml log. Did i forget a core mod or something else to add to my pack ?

https://gist.github.com/Dream-Master/3358ca118bca7ac56e5a#file-fml-log-bt

**Comment by fewizz** [comment]
fixed in 1.0.1. I'm stupid. -_-

**Comment by Dream-Master** [comment]
:+1:
